### PR TITLE
add COFs reported for C2-separation

### PR DESCRIPTION
**Pull request by mpougin**
@danieleongari I added 6 new COFs that were reported experimentally for C2-separation applications. For the older structures that are not in the DB so far, I received the crystallographic information directly from the authors

### CODE REVIEW

**Comment by mpougin** [comment]
the uniqueness check seems to detect similar structure graphs for 16130N3 and 16132N3.  16130N3 is the metalated version, it contains additional Ni-atoms, I am not sure why the ci-check doesn't detect this difference

**Comment by danieleongari** [comment]
Hi, @kjappelbaum's graph can not detects small differences, but it is anyway great for a rough check.
So, just add the pair in the whitelist https://github.com/danieleongari/CURATED-COFs/blob/6d512111f83ebc202bb2ef762899d95956dad1bc/.github/validate.py#L189-L205
and commit the change

thanks!

**Review by danieleongari — APPROVED** [review]
All fine for me thanks! merging

**Comment by mpougin** [comment]
great, thanks for the fast action @danieleongari

**Pull request merged**
