### PR TITLE
Structure Anomaly Corrections

### PR DESCRIPTION
**Pull request by eahenle**
Using the script `xtals_test1.jl`, I compiled lists of inputs that fail either the overlapping-atom load check or the bond inference sanity check.  The 3 structures in the former category have already been mentioned at #35.  The 64 structures in the latter category, I inspected visually via `xtals_test2.jl`.  Some were fine (unbound ions and hydrogen-bonded structures trigger warnings).  Some were a little odd: longer-than-normal bonds (`long_bonds`) or shorter-than-normal interatomic distances (`close_contacts`).  Finally, some were definitely erroneous (`bogus_C` and `bogus_H`).  The `reports` folder has the outputs for each of these categories, generated via `report_issues.jl`.

### CODE REVIEW

**Comment by danieleongari** [comment]
Hi @eahenle,
thank you very much for the great effort!

I would suggest, instead of adding reports that are too project-specific and are a bit obscure to read, to focus the effort on improving the [Continuous Integration hooks we have](https://github.com/danieleongari/CURATED-COFs/blob/master/.github/validate.py) to spot very basic problems. 
Note also that the philosophy of this repository is to provide raw CIFs that needs to be optimized to be considered "CURATED" and reported here: https://www.materialscloud.org/discover/curated-cofs#mcloudHeader
Therefore many of the problems you reported are fixed by optimization.

Identify problems is very project specific, so our purpose is to at least flag those problems that are not fixed by optimization and discard problematic CIFS: I think this is better for sake of simplicity.

**Comment by eahenle** [comment]
@danieleongari OK, gotcha.  I revised my analysis with all of that in mind, and found the following issues to still be attention-worthy:

~16056N2 orphan H~ [deleted extraneous H atoms]
~20340N2 missing C~ [added C atoms]
~20670N3 missing C~ [added C atom]
~21021N2 pentavalent C~ [removed extraneous C atoms]
21131N2 orphan H (if imine) / charge imbalance (if amine)
~21192N2 orphan H~ [removed extraneous H atoms]
21280N3 orphan H (I think--hard to tell what functional group the C-N-N-C moiety is supposed to be)
~21392N2 monovalent C~ [fixed with (PoreMatMod.jl)[https://github.com/SimonEnsemble/PoreMatMod.jl]]
~21551N3 bad H placement (may not converge in optimization)~ [moved H atoms to tenable positions]

I resolved the crossed-out issues above by editing the structures.  For the remaining two, I cannot tell what the correct structure is; I have therefore tentatively added them to the "cifs-discarded.csv" file.  I will fix them if you can tell me what they are.

I think it would be good to augment the CI to check structures with more than `ase.geometry.get_duplicate_atoms`.  This only detects atoms with coordinates within 0.1 Ang of each other, so it can miss other problems.  As for how to do that, exactly, I am unsure.  Xtals.jl could be used to flag added or modified CIFs that fail its loading/bonding checks for manual review (how I found the current structure issues).  The idea would be not to block the PR/commit, but just to encourage human verification.  If that sounds like something you'd like to have, I can make another PR.

**Comment by danieleongari** [comment]
Thank you very much, I appreciated!
I'll give a look in the weekend.

**Comment by danieleongari** [comment]
Hi @eahenle , 
we just merged the PR https://github.com/danieleongari/CURATED-COFs/pull/37 by @mpougin, who was working in parallel on fixing issues. 
Please, take the following actions:
- rebase, avoiding to correct twice structures already fixed in the other PR
- check that your PR does not modify the order or the style of the CIF: we need to keep exactly the same format because the CIF-parsing module of many programs is sloppy (being a very flexible format) and we want to avoid some structures to raise problems because of the slightly different formatting.
- check with @mpougin the cleaning actions, as some may need further discussion

I'll be away for a couple of week, so I already aligned with @mpougin to accept your contribution as soon as it is ok: she will take care of the review.

Thank again for your help!

**Comment by mpougin** [comment]
Thank you for the updates @eahenle. I will merge your PR once the tests finish

**Comment by eahenle** [comment]
Aha, we made the wrong correction in 21392N2, thus making it identical to 21393N2.  The mono-valent carbons should actually have been corrected to chlorine!  I will take care of that.

**Comment by mpougin** [comment]
great, thanks for spotting this

**Comment by mpougin** [comment]
all fine, I will merge now. Thanks again for your help @eahenle

**Review by mpougin — COMMENTED** [review]
anomalies spotted and edited correctly

**Comment by danieleongari** [comment]
Thanks @eahenle and @mpougin for your contribution! The PR looks clean to me.

**Pull request merged**
