### PR TITLE
add 69 papers, 194 cofs

### PR DESCRIPTION
**Pull request by mpougin**
update based on the list from Jul22

### CODE REVIEW

**Comment by mpougin** [comment]
@danieleongari , do you still have time to check here? Not sure what the problem is the pre-commit runs locally (see attached)
Screenshot 2023-08-26 at 15 35 54

**Comment by mpougin** [comment]
my environment 
[env.txt](https://github.com/danieleongari/CURATED-COFs/files/12445509/env.txt)

**Comment by danieleongari** [comment]
Ok to merge, I will fix the Github actions in the master,
it is probably due to some incompatibility in the package `monty` which is causing problem and  is `2022.3.12` in your env and `2023something` in the latest released used for the Github Action

**Comment by mpougin** [comment]
great thanks :)

**Pull request merged**
