### PR TITLE
October 2020 update

### PR DESCRIPTION
**Pull request by danieleongari**
Now submitting to nanoporous_screening to see if problems emerge.
There are structure of >3000 atoms (20480/1) that I will exclude.

### CODE REVIEW

**Comment by danieleongari** [comment]
@ltalirz it passed the pre-commit on my computer (see `CONTRIBUTING.md` ) and the one of CI.
Are these effective or there are more strict tests we may want to implement and test for this batch?

**Comment by ltalirz** [comment]
Good point - so far we're only checking whether there are duplicate DOIs
https://github.com/danieleongari/CURATED-COFs/blob/master/.github/validate.py

I'm happy to quickly add some additional tests that could make sens

**Comment by danieleongari** [comment]
Two further checks on the structures we might implement are:
* checking if they are P1 
* checking if the z dimension is larger than a threshold (no single layer CIFs)
* checking if there are not overlapping atoms (this will require ASE, pymatgen or manage_crystal)

**Comment by ltalirz** [comment]
@danieleongari Concerning the suggestions you make here, are you suggesting to add them in this DB or in https://github.com/lsmo-epfl/curated-cofs-submission ?

I guess we can have the second and third check here as well (e.g. to test older structures), but I'm wondering how you imagine implementing the P1 check in the CURATED-COFs repo - I thought all the files in this repo have passed through manage_crystal, which explicitly declares P1 symmetry.

**Pull request merged**
