### PR TITLE
check that structures are unique

### PR DESCRIPTION
**Pull request by ltalirz**
Use the mofchecker to check whether structures are unique

### CODE REVIEW

**Comment by ltalirz** [comment]
This adds both the check on the paper IDs and the uniqueness check on the structures.
I suspect the structure uniqueness check will take ~30 minutes

**Comment by ltalirz** [comment]
```
Warning: cifs/13051N2.cif and cifs/12000N2.cif have the same structure graph hash
Warning: cifs/13073N2.cif and cifs/13070N2.cif have the same structure graph hash
Warning: cifs/13101N2.cif and cifs/13100N2.cif have the same structure graph hash
Warning: cifs/14100N2.cif and cifs/11020N2.cif have the same structure graph hash
Warning: cifs/15130N2.cif and cifs/15110N2.cif have the same structure graph hash
Warning: cifs/15202N3.cif and cifs/15201N3.cif have the same structure graph hash
Warning: cifs/15230N2.cif and cifs/15210N2.cif have the same structure graph hash
Warning: cifs/16010N2.cif and cifs/08013N2.cif have the same structure graph hash
Warning: cifs/16082N2.cif and cifs/16080N2.cif have the same structure graph hash
Warning: cifs/16083N2.cif and cifs/16080N2.cif have the same structure graph hash
Warning: cifs/16220N2.cif and cifs/14090N2.cif have the same structure graph hash
Warning: cifs/16242C2.cif and cifs/16241C2.cif have the same structure graph hash
Warning: cifs/16251N3.cif and cifs/16250N3.cif have the same structure graph hash
Warning: cifs/16270N2.cif and cifs/14020N2.cif have the same structure graph hash
Warning: cifs/16300N2.cif and cifs/16142N2.cif have the same structure graph hash
Warning: cifs/16320N2.cif and cifs/13150N2.cif have the same structure graph hash
Warning: cifs/16330N2.cif and cifs/16090N2.cif have the same structure graph hash
Warning: cifs/16332N3.cif and cifs/15200N3.cif have the same structure graph hash
Warning: cifs/16381N2.cif and cifs/16142N2.cif have the same structure graph hash
Warning: cifs/16411C2.cif and cifs/16410C2.cif have the same structure graph hash
Warning: cifs/16412C2.cif and cifs/16410C2.cif have the same structure graph hash
Warning: cifs/16413C2.cif and cifs/16410C2.cif have the same structure graph hash
Warning: cifs/16470N2.cif and cifs/10020N2.cif have the same structure graph hash
Warning: cifs/16480N2.cif and cifs/16100N2.cif have the same structure graph hash
Warning: cifs/17010N2.cif and cifs/15163N2.cif have the same structure graph hash
Warning: cifs/17090N3.cif and cifs/13040N3.cif have the same structure graph hash
Warning: cifs/18021N3.cif and cifs/18020N3.cif have the same structure graph hash
Warning: cifs/18022N3.cif and cifs/18020N3.cif have the same structure graph hash
Warning: cifs/18023N3.cif and cifs/18020N3.cif have the same structure graph hash
Warning: cifs/18050N2.cif and cifs/16440N2.cif have the same structure graph hash
Warning: cifs/18132N3.cif and cifs/09000N3.cif have the same structure graph hash
Warning: cifs/18160N2.cif and cifs/16481N2.cif have the same structure graph hash
Warning: cifs/19001N3.cif and cifs/19000N3.cif have the same structure graph hash
Warning: cifs/19003N3.cif and cifs/19002N3.cif have the same structure graph hash
Warning: cifs/19231N2.cif and cifs/19230N2.cif have the same structure graph hash
Warning: cifs/19271N2.cif and cifs/19270N2.cif have the same structure graph hash
Warning: cifs/19340N2.cif and cifs/19300N2.cif have the same structure graph hash
  This can be done, for example using conda install openbabel"
Warning: cifs/19402N3.cif and cifs/19401N3.cif have the same structure graph hash
Warning: cifs/19403N3.cif and cifs/19401N3.cif have the same structure graph hash
Warning: cifs/19404N3.cif and cifs/19401N3.cif have the same structure graph hash
Warning: cifs/19431N2.cif and cifs/19350N2.cif have the same structure graph hash
Warning: cifs/20020N2.cif and cifs/13050N2.cif have the same structure graph hash
Warning: cifs/20111N3.cif and cifs/20110N3.cif have the same structure graph hash
Warning: cifs/20112N3.cif and cifs/20110N3.cif have the same structure graph hash
Warning: cifs/20115N3.cif and cifs/20114N3.cif have the same structure graph hash
Warning: cifs/20118N3.cif and cifs/20117N3.cif have the same structure graph hash
Warning: cifs/20164N2.cif and cifs/20163N2.cif have the same structure graph hash
Warning: cifs/20173N2.cif and cifs/20172N2.cif have the same structure graph hash
Warning: cifs/20200N2.cif and cifs/16271N2.cif have the same structure graph hash
Warning: cifs/20211N2.cif and cifs/18141N2.cif have the same structure graph hash
Warning: cifs/20280N2.cif and cifs/20230N2.cif have the same structure graph hash
Warning: cifs/20330N2.cif and cifs/19360N2.cif have the same structure graph hash
Warning: cifs/20491N2.cif and cifs/20490N2.cif have the same structure graph hash
Warning: cifs/20501N3.cif and cifs/20500N3.cif have the same structure graph hash
Warning: cifs/20641N2.cif and cifs/15163N2.cif have the same structure graph hash
Warning: cifs/21001N2.cif and cifs/20130N2.cif have the same structure graph hash
Warning: cifs/21032N2.cif and cifs/21030N2.cif have the same structure graph hash
Warning: cifs/21034N2.cif and cifs/21033N2.cif have the same structure graph hash
Warning: cifs/21035N2.cif and cifs/21031N2.cif have the same structure graph hash
Warning: cifs/21083N2.cif and cifs/20600N2.cif have the same structure graph hash
Warning: cifs/21091N3.cif and cifs/21090N3.cif have the same structure graph hash
```

**Comment by danieleongari** [comment]
Hi, what's the status here? I'll rebase when it is ready.
I saw the paper<>framework check, but another it is missing is the CIF<>framework.csv check. Thanks

**Comment by ltalirz** [comment]
>  another it is missing is the CIF<>framework.csv check

Ok, I wasn't aware you wanted to have a check for that as well. That's easy to add.
In the meanwhile perhaps have a look at the structures that are flagged as identical

**Review by danieleongari — APPROVED** [review]
Thanks, 
1) Is there also a check for the CIF filename <> ID in frameworks.csv?
2) I'll see if the plan to plane correction is not going to be too painful for merging my update (having to select the version one by one)
3) if the graph takes so long, is there a way to disable it by default and run it time to time? One would like to specifically tackle that in a further check rather than at commit.

**Comment by ltalirz** [comment]
> 3\. if the graph takes so long, is there a way to disable it by default and run it time to time? One would like to specifically tackle that in a further check rather than at commit.

In the end, this is a matter of policy (we can simply decide to ignore it when making quick changes).
One could remove it from CI entirely - or one could run it every day/week/month but in the end I think we can also just leave it running on each commit.

At some point I wanted to give a look into speeding up the graph generation (which would need to be done in pymatgen); that would then hopefully make that check faster

**Comment by kjappelbaum** [comment]
>At some point I wanted to give a look into speeding up the graph generation (which would need to be done in pymatgen); that would then hopefully make that check faster

something that would be quite valuable in many applications (also several GCNN packages depend on the pymatgen StructureGraph) but likely a time-consuming rabbithole (which is the reason i avoided it thus far). One thing is likely a more efficient neighbor search(e.g.,  using grid hashing) and most likely one could also cache quite a lot of stuff due to symmetry.

**Comment by danieleongari** [comment]
@ltalirz 
Just noticed you commented
```
# from pymatgen.io.cif import CifParser
# from mofchecker import MOFChecker
```
Why? The test is failing because there is no CifParser.
BTW, I see that the unique-COF check is done only on GitHub, not on the local computer. This is fine: I thought one had to wait to commit.

**Comment by ltalirz** [comment]
sorry - I commented it because it did not properly install in my local environment.
Please uncomment

**Pull request merged**
